# Generated by Django 5.2.1 on 2025-07-10 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savileaf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='content',
        ),
        migrations.RemoveField(
            model_name='service',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='show_in_navbar',
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_image',
            field=models.ImageField(null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_paragraph',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='savileaf.service')),
            ],
        ),
    ]
