# Generated by Django 5.2.1 on 2025-07-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savileaf', '0002_remove_service_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='features_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
