# Generated by Django 5.2.1 on 2025-07-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savileaf', '0003_feature_features_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='features_image',
        ),
        migrations.AddField(
            model_name='service',
            name='detail_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='features_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='hero_heading',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='hero_paragraph',
            field=models.TextField(blank=True, default=''),
        ),
    ]
