# Generated by Django 5.2.1 on 2025-07-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savileaf', '0004_remove_feature_features_image_service_detail_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='detail_title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='features_image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='hero_heading',
        ),
        migrations.RemoveField(
            model_name='service',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='hero_paragraph',
        ),
        migrations.RemoveField(
            model_name='service',
            name='overview',
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='service-icons/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
