# Generated by Django 5.2.1 on 2025-07-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savileaf', '0005_remove_service_detail_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Text to display in the dropdown', max_length=100)),
                ('url_name', models.CharField(help_text='The name of the URL pattern', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the menu items')),
                ('active', models.BooleanField(default=True, help_text='Show this item in the dropdown')),
            ],
            options={
                'verbose_name': 'Dropdown Menu Item',
                'verbose_name_plural': 'Dropdown Menu Items',
                'ordering': ['order'],
            },
        ),
    ]
