# Generated by Django 5.2.1 on 2025-07-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savileaf', '0006_dropdownmenuitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='dropdownmenuitem',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dropdownmenuitem',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/hero/'),
        ),
        migrations.AddField(
            model_name='dropdownmenuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='dropdownmenuitem',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dropdownmenuitem',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dropdownmenuitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dropdownmenuitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dropdownmenuitem',
            name='url_name',
            field=models.SlugField(help_text='Slug used in URL: /services/<slug>/', unique=True),
        ),
    ]
