# Generated by Django 5.2.1 on 2025-07-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savileaf', '0007_delete_service_dropdownmenuitem_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdownmenuitem',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
