# Generated by Django 5.2.1 on 2025-07-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savileaf', '0008_dropdownmenuitem_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Name of the service to show', max_length=100)),
                ('url_name', models.CharField(help_text='Django URL pattern name', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Footer Service',
                'verbose_name_plural': 'Footer Services',
                'ordering': ['order'],
            },
        ),
    ]
