# Generated by Django 5.2.1 on 2025-07-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savileaf', '0009_footerservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerservice',
            options={},
        ),
        migrations.RemoveField(
            model_name='footerservice',
            name='active',
        ),
        migrations.RemoveField(
            model_name='footerservice',
            name='label',
        ),
        migrations.RemoveField(
            model_name='footerservice',
            name='order',
        ),
        migrations.AddField(
            model_name='footerservice',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='footerservice',
            name='url_name',
            field=models.CharField(help_text='Enter the Django URL pattern name', max_length=100, null=True),
        ),
    ]
