# Generated by Django 5.2.1 on 2025-07-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savileaf', '0010_alter_footerservice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerservice',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug used in the URL', max_length=200, null=True),
        ),
    ]
