# Generated by Django 5.2.1 on 2025-07-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savileaf', '0011_footerservice_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdownmenuitem',
            name='section_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
